### PR TITLE
MODULES-11423: add zfs attribute defaultuserquota

### PR DESCRIPTION
**Pull request by eg-roberts**
May we please add the zfs attribute 'defaultuserquota' to the zfs type/provider?

### CODE REVIEW

**Comment by joshcooper** [comment]
@eg-roberts thank you for your contribution! Could you sign the CLA?

**Review by joshcooper — CHANGES_REQUESTED** [review]
Thanks @eg-roberts! This will need a few tweaks to wrap up.

Can you add `newproperty(:defaultuserquota)` to the `zfs` type here https://github.com/puppetlabs/puppetlabs-zfs_core/blob/393b74c2817597015d4b9a0803f1df84dd0136aa/lib/puppet/type/zfs.rb#L55-L61

Then use this rake task to autogenerate the reference:

```
$ bundle install
$ bundle exec rake strings:generate:reference
...
```

And include the modified `REFERENCE.md` in your commit.

**Comment by joshcooper** [comment]
Hi @eg-roberts friendly ping to see if you can update your PR?

**Review by h0tw1r3 — APPROVED** [review]

**Comment by joshcooper** [comment]
@h0tw1r3 was the bcrypt native extension issue resolved? Maybe that was in bolt?

**Comment by h0tw1r3** [comment]
> @h0tw1r3 was the bcrypt native extension issue resolved? Maybe that was in bolt?

@joshcooper, yes it was updated in Puppet runtime, https://github.com/puppetlabs/puppet-runtime/pull/854
but still needs including in bolt https://github.com/puppetlabs/bolt/pull/3248

**Review by joshcooper — APPROVED** [review]

**Comment by AriaXLi** [comment]
Hi again @h0tw1r3 thanks again for contributing! Like `relatime`, `defaultuserquote` attribute is causing some errors in CI that lead me to believe this attribute may also only be supported on Linux. 
```
00:28:33   Error: Could not run: Execution of '/usr/sbin/zfs get -H -o value defaultuserquota tstpool/tstfs' returned 2: bad property list: invalid property 'defaultuserquota'
00:28:35   For more info, run: zfs help get
```

When you can, could you please update this PR too to account for this?
We have some other Linux-only properties that handle this in type (for `overlay`):
https://github.com/puppetlabs/puppetlabs-zfs_core/blob/e16b1c2b8487ef4cfc71f4388003b8c623b47cb0/lib/puppet/type/zfs.rb#L83-L89

Or in provider (for `aclmode`): https://github.com/puppetlabs/puppetlabs-zfs_core/blob/e16b1c2b8487ef4cfc71f4388003b8c623b47cb0/lib/puppet/provider/zfs/zfs.rb#L60-L69

**Comment by h0tw1r3** [comment]
@AriaXLi I'm not working at Puppet any longer and this is an **internal** CI issue. Someone else will need to pick this up.

**Comment by mhashizume** [comment]
Adding the "skip changelog" label to this PR since it was superseded by https://github.com/puppetlabs/puppetlabs-zfs_core/pull/83

**Pull request merged**
